### ISSUE TITLE
Incorrect File Path

### ISSUE THREAD

**Issue by kapisz** [vimeo/VIMUpload#23]
I'm attempting to capture a video within the application when not connected to the internet and upload the video at a later time. The issue that I'm having is that the library retains a reference to the AVURLAsset with an _**absolute**_ file path which is no longer safe to assume (as described in Apple's technical note: https://developer.apple.com/library/ios/technotes/tn2406/_index.html) and consequently the library is unable to infer the video's location when the task queue resumes after the application has been terminated. Will this (hopefully) be fixed before the release of 2.0?

Best Regards,
Rob

**Comment by alfiehanssen** [comment]
@kapisz We're actually replacing VIMUpload with a new, Swift library: 

https://github.com/vimeo/VimeoUpload

It was open sourced earlier this week. It's at v0.9 at the moment and is in use in the App Store version of the new Vimeo iOS app. It drives all uploads and downloads in the app. 

I suggest checking it out and using it instead of VIMUpload.

**Comment by alfiehanssen** [comment]
(We are no longer actively maintaining VIMUpload.)
